from enum import Enum


class ErrorCategory(str, Enum):

    INVALID_STRUCTURE = "INVALID_STRUCTURE"

    MISSING_FIELDS = "MISSING_FIELDS"

    LOW_COVERAGE = "LOW_COVERAGE"

    INCONSISTENT_COMPONENTS = "INCONSISTENT_COMPONENTS"

    INCOMPLETE_DOCUMENTATION = "INCOMPLETE_DOCUMENTATION"

    FATAL_CONFIGURATION = "FATAL_CONFIGURATION"

    UNKNOWN_ERROR = "UNKNOWN_ERROR"